format: yamanifest
version: 1.0
---
work/access-om3-MOM6-CICE6:
  fullpath: /g/data/gv90/da1339/spack/0.22/environments/om3_cice6_dev/.spack-env/view/bin/access-om3-MOM6-CICE6
  hashes:
    binhash: 722a2daa4f560a8f7d2eec03a38a032d
    md5: c7b2d2138b95c14148c1de50afc8cd95
